-- Derived team-match feature schema for the Sofascore player-stat pipeline.

CREATE SCHEMA IF NOT EXISTS features;

CREATE TABLE IF NOT EXISTS features.sofascore_team_match_aggregates (
    match_id BIGINT NOT NULL,
    sofascore_event_id BIGINT NOT NULL,
    season_id BIGINT NOT NULL,
    season_year TEXT NOT NULL,
    start_timestamp BIGINT NOT NULL,
    start_datetime TIMESTAMPTZ NOT NULL,
    match_date DATE NOT NULL,
    team_id BIGINT NOT NULL,
    opponent_id BIGINT NOT NULL,
    team_name TEXT NOT NULL,
    opponent_name TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('home', 'away')),
    goals_for INTEGER,
    goals_against INTEGER,
    active_player_count INTEGER NOT NULL,
    total_team_minutes NUMERIC,

    xg NUMERIC,
    xa NUMERIC,
    key_passes NUMERIC,
    big_chances NUMERIC,
    total_shots NUMERIC,
    shots_on_target NUMERIC,
    interceptions NUMERIC,
    tackles NUMERIC,
    blocks NUMERIC,
    aerial_won NUMERIC,
    aerial_lost NUMERIC,
    accurate_pass NUMERIC,
    total_pass NUMERIC,
    touches NUMERIC,
    long_balls NUMERIC,
    accurate_long_balls NUMERIC,
    progressive_carries NUMERIC,
    possession_lost_ctrl NUMERIC,
    saves NUMERIC,
    goals_prevented NUMERIC,

    xg_against NUMERIC,
    shots_against NUMERIC,
    big_chances_against NUMERIC,
    shots_on_target_against NUMERIC,

    pass_accuracy NUMERIC,
    aerial_win_rate NUMERIC,
    shot_accuracy NUMERIC,
    possession_proxy NUMERIC,
    passes_per_minute NUMERIC,
    saves_per_shot_faced NUMERIC,
    tackles_interceptions NUMERIC,

    has_xg BOOLEAN NOT NULL DEFAULT false,
    has_xa BOOLEAN NOT NULL DEFAULT false,
    has_key_passes BOOLEAN NOT NULL DEFAULT false,
    has_big_chances BOOLEAN NOT NULL DEFAULT false,
    has_total_shots BOOLEAN NOT NULL DEFAULT false,
    has_shots_on_target BOOLEAN NOT NULL DEFAULT false,
    has_interceptions BOOLEAN NOT NULL DEFAULT false,
    has_tackles BOOLEAN NOT NULL DEFAULT false,
    has_blocks BOOLEAN NOT NULL DEFAULT false,
    has_aerial_won BOOLEAN NOT NULL DEFAULT false,
    has_aerial_lost BOOLEAN NOT NULL DEFAULT false,
    has_accurate_pass BOOLEAN NOT NULL DEFAULT false,
    has_total_pass BOOLEAN NOT NULL DEFAULT false,
    has_touches BOOLEAN NOT NULL DEFAULT false,
    has_long_balls BOOLEAN NOT NULL DEFAULT false,
    has_accurate_long_balls BOOLEAN NOT NULL DEFAULT false,
    has_progressive_carries BOOLEAN NOT NULL DEFAULT false,
    has_possession_lost_ctrl BOOLEAN NOT NULL DEFAULT false,
    has_saves BOOLEAN NOT NULL DEFAULT false,
    has_goals_prevented BOOLEAN NOT NULL DEFAULT false,

    xg_player_count INTEGER NOT NULL DEFAULT 0,
    xa_player_count INTEGER NOT NULL DEFAULT 0,
    key_passes_player_count INTEGER NOT NULL DEFAULT 0,
    big_chances_player_count INTEGER NOT NULL DEFAULT 0,
    total_shots_player_count INTEGER NOT NULL DEFAULT 0,
    shots_on_target_player_count INTEGER NOT NULL DEFAULT 0,
    interceptions_player_count INTEGER NOT NULL DEFAULT 0,
    tackles_player_count INTEGER NOT NULL DEFAULT 0,
    blocks_player_count INTEGER NOT NULL DEFAULT 0,
    aerial_won_player_count INTEGER NOT NULL DEFAULT 0,
    aerial_lost_player_count INTEGER NOT NULL DEFAULT 0,
    accurate_pass_player_count INTEGER NOT NULL DEFAULT 0,
    total_pass_player_count INTEGER NOT NULL DEFAULT 0,
    touches_player_count INTEGER NOT NULL DEFAULT 0,
    long_balls_player_count INTEGER NOT NULL DEFAULT 0,
    accurate_long_balls_player_count INTEGER NOT NULL DEFAULT 0,
    progressive_carries_player_count INTEGER NOT NULL DEFAULT 0,
    possession_lost_ctrl_player_count INTEGER NOT NULL DEFAULT 0,
    saves_player_count INTEGER NOT NULL DEFAULT 0,
    goals_prevented_player_count INTEGER NOT NULL DEFAULT 0,

    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (match_id, team_id)
);

CREATE TABLE IF NOT EXISTS features.sofascore_team_match_features (
    match_id BIGINT NOT NULL,
    sofascore_event_id BIGINT NOT NULL,
    season_id BIGINT NOT NULL,
    season_year TEXT NOT NULL,
    start_timestamp BIGINT NOT NULL,
    start_datetime TIMESTAMPTZ NOT NULL,
    match_date DATE NOT NULL,
    team_id BIGINT NOT NULL,
    opponent_id BIGINT NOT NULL,
    team_name TEXT NOT NULL,
    opponent_name TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('home', 'away')),
    goals_for INTEGER,
    goals_against INTEGER,
    active_player_count INTEGER NOT NULL,
    total_team_minutes NUMERIC,

    xg NUMERIC,
    xa NUMERIC,
    key_passes NUMERIC,
    big_chances NUMERIC,
    total_shots NUMERIC,
    shots_on_target NUMERIC,
    interceptions NUMERIC,
    tackles NUMERIC,
    blocks NUMERIC,
    aerial_won NUMERIC,
    aerial_lost NUMERIC,
    accurate_pass NUMERIC,
    total_pass NUMERIC,
    touches NUMERIC,
    long_balls NUMERIC,
    accurate_long_balls NUMERIC,
    progressive_carries NUMERIC,
    possession_lost_ctrl NUMERIC,
    saves NUMERIC,
    goals_prevented NUMERIC,

    xg_against NUMERIC,
    shots_against NUMERIC,
    big_chances_against NUMERIC,
    shots_on_target_against NUMERIC,

    pass_accuracy NUMERIC,
    aerial_win_rate NUMERIC,
    shot_accuracy NUMERIC,
    possession_proxy NUMERIC,
    passes_per_minute NUMERIC,
    saves_per_shot_faced NUMERIC,
    tackles_interceptions NUMERIC,

    has_xg BOOLEAN NOT NULL DEFAULT false,
    has_xa BOOLEAN NOT NULL DEFAULT false,
    has_key_passes BOOLEAN NOT NULL DEFAULT false,
    has_big_chances BOOLEAN NOT NULL DEFAULT false,
    has_total_shots BOOLEAN NOT NULL DEFAULT false,
    has_shots_on_target BOOLEAN NOT NULL DEFAULT false,
    has_interceptions BOOLEAN NOT NULL DEFAULT false,
    has_tackles BOOLEAN NOT NULL DEFAULT false,
    has_blocks BOOLEAN NOT NULL DEFAULT false,
    has_aerial_won BOOLEAN NOT NULL DEFAULT false,
    has_aerial_lost BOOLEAN NOT NULL DEFAULT false,
    has_accurate_pass BOOLEAN NOT NULL DEFAULT false,
    has_total_pass BOOLEAN NOT NULL DEFAULT false,
    has_touches BOOLEAN NOT NULL DEFAULT false,
    has_long_balls BOOLEAN NOT NULL DEFAULT false,
    has_accurate_long_balls BOOLEAN NOT NULL DEFAULT false,
    has_progressive_carries BOOLEAN NOT NULL DEFAULT false,
    has_possession_lost_ctrl BOOLEAN NOT NULL DEFAULT false,
    has_saves BOOLEAN NOT NULL DEFAULT false,
    has_goals_prevented BOOLEAN NOT NULL DEFAULT false,

    xg_player_count INTEGER NOT NULL DEFAULT 0,
    xa_player_count INTEGER NOT NULL DEFAULT 0,
    key_passes_player_count INTEGER NOT NULL DEFAULT 0,
    big_chances_player_count INTEGER NOT NULL DEFAULT 0,
    total_shots_player_count INTEGER NOT NULL DEFAULT 0,
    shots_on_target_player_count INTEGER NOT NULL DEFAULT 0,
    interceptions_player_count INTEGER NOT NULL DEFAULT 0,
    tackles_player_count INTEGER NOT NULL DEFAULT 0,
    blocks_player_count INTEGER NOT NULL DEFAULT 0,
    aerial_won_player_count INTEGER NOT NULL DEFAULT 0,
    aerial_lost_player_count INTEGER NOT NULL DEFAULT 0,
    accurate_pass_player_count INTEGER NOT NULL DEFAULT 0,
    total_pass_player_count INTEGER NOT NULL DEFAULT 0,
    touches_player_count INTEGER NOT NULL DEFAULT 0,
    long_balls_player_count INTEGER NOT NULL DEFAULT 0,
    accurate_long_balls_player_count INTEGER NOT NULL DEFAULT 0,
    progressive_carries_player_count INTEGER NOT NULL DEFAULT 0,
    possession_lost_ctrl_player_count INTEGER NOT NULL DEFAULT 0,
    saves_player_count INTEGER NOT NULL DEFAULT 0,
    goals_prevented_player_count INTEGER NOT NULL DEFAULT 0,

    history_match_count INTEGER NOT NULL,
    rolling_xg_for_available_count INTEGER NOT NULL,
    rolling_xg_against_available_count INTEGER NOT NULL,
    rolling_shots_for_available_count INTEGER NOT NULL,
    rolling_shots_against_available_count INTEGER NOT NULL,
    rolling_big_chances_for_available_count INTEGER NOT NULL,
    rolling_big_chances_against_available_count INTEGER NOT NULL,
    rolling_possession_proxy_available_count INTEGER NOT NULL,
    rolling_pass_accuracy_available_count INTEGER NOT NULL,
    rolling_tackles_interceptions_available_count INTEGER NOT NULL,
    rolling_saves_per_shot_faced_available_count INTEGER NOT NULL,

    rolling_xg_for NUMERIC,
    rolling_xg_against NUMERIC,
    rolling_shots_for NUMERIC,
    rolling_shots_against NUMERIC,
    rolling_big_chances_for NUMERIC,
    rolling_big_chances_against NUMERIC,
    rolling_possession_proxy NUMERIC,
    rolling_pass_accuracy NUMERIC,
    rolling_tackles_interceptions NUMERIC,
    rolling_saves_per_shot_faced NUMERIC,

    opponent_history_match_count INTEGER,
    opponent_rolling_xg_for NUMERIC,
    opponent_rolling_xg_against NUMERIC,
    opponent_rolling_shots_for NUMERIC,
    opponent_rolling_shots_against NUMERIC,

    adj_attack_xg NUMERIC,
    adj_defence_xg NUMERIC,
    adj_shot_volume NUMERIC,

    refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (match_id, team_id)
);

CREATE INDEX IF NOT EXISTS idx_sofascore_team_aggregates_season_date
    ON features.sofascore_team_match_aggregates (season_year, match_date);

CREATE INDEX IF NOT EXISTS idx_sofascore_team_aggregates_team_form
    ON features.sofascore_team_match_aggregates (team_id, season_year, start_datetime);

CREATE INDEX IF NOT EXISTS idx_sofascore_team_aggregates_match_team
    ON features.sofascore_team_match_aggregates (match_id, team_id);

CREATE INDEX IF NOT EXISTS idx_sofascore_team_features_season_date
    ON features.sofascore_team_match_features (season_year, match_date);

CREATE INDEX IF NOT EXISTS idx_sofascore_team_features_team_form
    ON features.sofascore_team_match_features (team_id, season_year, start_datetime);

CREATE INDEX IF NOT EXISTS idx_sofascore_team_features_match_team
    ON features.sofascore_team_match_features (match_id, team_id);
